version: 1.0.{build}
os: Visual Studio 2015
configuration: Release
init:
- cmd: dnvm install 1.0.0-rc1-update1
before_build:
- cmd: dnu restore
build:
  verbosity: minimal
test_script:
- cmd: dnx -p tests\PcgRandom.Tests test