version: 1.0.{build}
os: Visual Studio 2015
configuration: Release
init:
- cmd: >-
    choco install dotnetcore -version 1.0.0.001598

    set PATH=C:\Program Files\dotnet\bin;%PATH%
before_build:
- cmd: dotnet restore
build_script:
- cmd: dotnet build src\PcgRandom
test_script:
- cmd: >-
    cd tests\PcgRandom.Tests

    dotnet restore

    dotnet test